// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdKK_8TonQhQ2F7zZba07t2aJMgQOIc-M',
    appId: '1:718331653773:web:c5b67d2260a706ac8f3cc4',
    messagingSenderId: '718331653773',
    projectId: 'linuxapp-b1edf',
    authDomain: 'linuxapp-b1edf.firebaseapp.com',
    storageBucket: 'linuxapp-b1edf.appspot.com',
    measurementId: 'G-3K9EJFMXP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwDSJuCFr71VdFzSXAHUhp4c9ipS8_aY',
    appId: '1:718331653773:android:589076478e7783718f3cc4',
    messagingSenderId: '718331653773',
    projectId: 'linuxapp-b1edf',
    storageBucket: 'linuxapp-b1edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC68LesMUVXtkWaWRHtTm5qG0CEoV7hVmw',
    appId: '1:718331653773:ios:c77ba7abcd46d9f18f3cc4',
    messagingSenderId: '718331653773',
    projectId: 'linuxapp-b1edf',
    storageBucket: 'linuxapp-b1edf.appspot.com',
    iosClientId: '718331653773-lscoeoja9e5fnmhn9f42pear2ivq6n0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.linuxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC68LesMUVXtkWaWRHtTm5qG0CEoV7hVmw',
    appId: '1:718331653773:ios:c77ba7abcd46d9f18f3cc4',
    messagingSenderId: '718331653773',
    projectId: 'linuxapp-b1edf',
    storageBucket: 'linuxapp-b1edf.appspot.com',
    iosClientId: '718331653773-lscoeoja9e5fnmhn9f42pear2ivq6n0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.linuxApp',
  );
}
